FROM node:20-alpine AS builder
RUN apk add --no-cache libc6-compat chromium nss freetype harfbuzz ca-certificates ttf-freefont python3 make g++
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
WORKDIR /app

COPY package.json ./
RUN npm install && npm cache clean --force

COPY . .

ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG R2_ENDPOINT
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG R2_PUBLIC_URL
ARG OPENAI_IMAGE_API_KEY
ARG OPENAI_IMAGE_API_BASE
ARG IMAGE_MODEL
ARG TEXT_API_KEY
ARG TEXT_API_BASE
ARG TEXT_MODEL
ARG ADMIN_PASSWORD
ARG DATABASE_URL

ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_KEY=${SUPABASE_KEY}
ENV SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENV R2_ENDPOINT=${R2_ENDPOINT}
ENV R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
ENV R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
ENV R2_BUCKET_NAME=${R2_BUCKET_NAME}
ENV R2_PUBLIC_URL=${R2_PUBLIC_URL}
ENV OPENAI_IMAGE_API_KEY=${OPENAI_IMAGE_API_KEY}
ENV OPENAI_IMAGE_API_BASE=${OPENAI_IMAGE_API_BASE}
ENV IMAGE_MODEL=${IMAGE_MODEL}
ENV TEXT_API_KEY=${TEXT_API_KEY}
ENV TEXT_API_BASE=${TEXT_API_BASE}
ENV TEXT_MODEL=${TEXT_MODEL}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}

RUN npm run build

FROM node:20-alpine AS runner
RUN apk add --no-cache libc6-compat chromium nss freetype harfbuzz ca-certificates ttf-freefont
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npx", "next", "start"]
